// nuxt/pages/projects.vue
<script setup lang="ts">
const description = `some of my projects i've been working on recently.`
const title = 'ryan voitiskis - projects'
const url = 'https://ryanvoitiskis.com/projects'
const crateGuideImage =
	'https://ryanvoitiskis.com/img/projects/crate_guide_screenshot_1.png'
useHead({
	title: title,
	meta: [
		{ name: 'description', content: description },
		{ property: 'og:title', content: title },
		{ property: 'og:description', content: description },
		{ property: 'og:url', content: url },
		{ property: 'og:image', content: crateGuideImage },
		{ property: 'twitter:card', content: 'summary_large_image' },
		{ property: 'twitter:title', content: title },
		{ property: 'twitter:description', content: description },
		{ property: 'twitter:image', content: crateGuideImage }
	],
	link: [{ rel: 'canonical', href: url }]
})

const crateGuideImages = [
	{
		src: '/img/projects/crate_guide_screenshot_1.png',
		alt: 'Crate Guide empty deck interface.'
	},
	{
		src: '/img/projects/crate_guide_screenshot_0.jpeg',
		alt: 'Crate Guide loaded single deck interface.'
	},
	{
		src: '/img/projects/crate_guide_screenshot_2.png',
		alt: 'Crate Guide empty deck interface.'
	},
	{
		src: '/img/projects/crate_guide_screenshot_3.png',
		alt: 'Crate Guide track select interface.'
	},
	{
		src: '/img/projects/crate_guide_screenshot_4.png',
		alt: 'Crate Guide login interface.'
	}
]

const panelLayoutImages = [
	{
		src: '/img/projects/panel-layout-generator_screenshot_0.png',
		alt: 'panel-layout-generator interface.'
	},
	{
		src: '/img/projects/panel-layout-generator_screenshot_1.png',
		alt: 'panel-layout-generator interface with numbers.'
	},
	{
		src: '/img/projects/panel-layout-generator_screenshot_2.png',
		alt: 'panel-layout-generator interface with 960 panels.'
	}
]
</script>

<template>
	<main class="mx-auto w-full max-w-[1120px] px-4 pb-48">
		<h1 class="font-mono text-sm font-[120] text-muted-foreground">
			> projects
		</h1>

		<article
			class="mx-auto flex flex-col items-center gap-4 border-b py-16 lg:flex-row lg:gap-16 lg:py-24"
		>
			<div class="lg:order-last">
				<h2 class="font-mono font-bold">Crate Guide</h2>
				<div class="my-2 flex flex-wrap gap-2">
					<Badge text="Vue.js" />
					<Badge text="PWA" />
					<Badge text="desktop" />
				</div>
				<div class="mb-2 text-sm">
					<!-- prettier-ignore -->
					<a href="https://crate.guide" class="font-mono font-[130]">crate.guide</a>
					&nbsp;|&nbsp;
					<a
						href="https://github.com/ryan-voitiskis/crate-guide"
						class="font-mono font-[130]"
					>
						GitHub
					</a>
				</div>
				<p>
					Crate Guide is a DJ app designed to assist in finding compatible
					tracks within a users physical record collection. Records can be added
					manually or imported from your Discogs collection. Audio features from
					your tracks can then be imported from Spotify through a mostly
					automated process.
				</p>
				<p>
					The app was built using Vue.js for the front-end and Express.js on the
					back-end connecting to a MongoDB database. Authenticated requests are
					made to the Discogs API using OAuth 1.0, and OAuth 2.0 with the
					Spotify API.
				</p>
			</div>
			<Carousel
				class="max-w-screen-xs focus-visible:!ring-8 focus-visible:ring-ring"
			>
				<CarouselContent>
					<CarouselItem v-for="(img, i) in crateGuideImages" :key="i">
						<NuxtImg
							class="w-full self-center object-contain"
							:src="img.src"
							:alt="img.alt"
							:preload="i === 0"
							format="webp"
						/>
					</CarouselItem>
				</CarouselContent>
				<div class="flex justify-center gap-4">
					<CarouselPrevious />
					<CarouselNext />
				</div>
			</Carousel>
		</article>

		<article
			class="mx-auto flex flex-col items-center gap-4 border-b py-16 md:flex-row md:gap-16 lg:py-24"
		>
			<div>
				<h2 class="mb-4 font-mono font-bold">bpm tap</h2>
				<div class="my-2 flex flex-wrap gap-2">
					<Badge text="Vue.js" />
					<Badge text="PWA" />
					<Badge text="D3.js" />
				</div>
				<div class="mb-2 text-sm">
					<!-- prettier-ignore -->
					<a href="https://bpm-tap-0.netlify.app/" class="font-mono font-[130]">bpm-tap-0.netlify.app</a>
					&nbsp;|&nbsp;
					<a
						href="https://github.com/ryan-voitiskis/bpm-tap"
						class="font-mono font-[130]"
					>
						GitHub
					</a>
				</div>
				<p>
					bpm tap is an extremely simple web app for tapping out the tempo of a
					song. I needed a solution for comparing the tempo of two tracks that
					could be installed on a phone quickly. The app is designed to be used
					as a PWA on a phone, with the tempo being tapped out by tapping the
					screen. The tempo is displayed in real-time and can be reset by not
					tapping for 2 seconds.
				</p>
				<p>
					To save a tempo as a reference for future measurements, the user can
					lock the most recent bpm by enabling the lock feature with the lock
					icon button at the top right. My use case for this is to compare the
					tempo of a track I'm playing to the tempo of the next track I want to
					mix in.
				</p>
				<p>
					The app uses
					<a href="https://d3js.org/d3-interpolate/color">
						D3.js colour interpolation
					</a>
					to represent the tempo as a background colour, providing a visual aid
					for comparing the currently tapped tempo with the last or lock bpm.
				</p>
			</div>
			<PhoneMockup>
				<iframe
					title="bpm-tap-0.netlify.app"
					src="https://demo--bpm-tap-0.netlify.app/"
					class="h-full w-full"
				/>
			</PhoneMockup>
		</article>

		<article
			class="mx-auto flex flex-col items-center gap-4 py-16 lg:flex-row lg:gap-16 lg:py-24"
		>
			<div class="lg:order-last">
				<h2 class="font-mono font-bold">Panel layout generator</h2>
				<div class="my-2 flex flex-wrap gap-2">
					<Badge text="Vue.js" />
					<Badge text="SPA" />
				</div>
				<div class="mb-2 text-sm">
					<!-- prettier-ignore -->
					<a href="https://panel-layout-generator.com" class="font-mono font-[130]">panel-layout-generator.com</a>
					&nbsp;|&nbsp;
					<a
						href="https://github.com/ryan-voitiskis/panel-layout-generator"
						class="font-mono font-[130]"
					>
						GitHub
					</a>
				</div>
				<p>
					Panel layout generator is a simple layout generator for square
					acoustic panel installations. A friend of mine was installing acoustic
					panels using a variety of colours. Since his installations were
					constrained by specific quantities of each colour, and he did not want
					adjacent panels to be of the same colour, he had to plan the layout
					carefully. This app is a quick solution I threw together to solve his
					problem. Panel colours can be added with their quantities and the
					number of rows and columns adjusted. A random layout is generated upon
					any changes.
				</p>
				<p>
					The app was built using Vue.js, with the only other dependencies being
					<a href="https://pinia.vuejs.org/">Pinia</a>
					and
					<a href="https://vue-accessible-color-picker.netlify.app/">
						vue-accessible-color-picker.
					</a>
				</p>
			</div>
			<Carousel
				class="max-w-screen-sm focus-visible:!ring-8 focus-visible:ring-ring"
			>
				<CarouselContent>
					<CarouselItem v-for="(img, i) in panelLayoutImages" :key="i">
						<NuxtImg
							class="w-full object-contain"
							:src="img.src"
							:alt="img.alt"
							format="webp"
						/>
					</CarouselItem>
				</CarouselContent>
				<div class="flex justify-center gap-4">
					<CarouselPrevious />
					<CarouselNext />
				</div>
			</Carousel>
		</article>
	</main>
</template>

// OLD/src/routes/projects/+page.svelte
<script lang="ts">
	import type { PageData } from './$types'
	import crateGuideImage from '$lib/images/crate-guide.jpeg'
	import panelLayoutGeneratorImage from '$lib/images/panel-layout-generator.png'
	export let data: PageData
</script>

<div class="intro">
	<h1>Projects</h1>
	<p>
		Here's a couple of projects I've been working on recently. I would love to hear your feeback at <a
			href="mailto:ryanvoitiskis@pm.me">ryanvoitiskis@pm.me</a
		>
	</p>
	<br />
</div>

<article class="project">
	<a href="https://crate.guide" class="image-stack clean">
		<img src={crateGuideImage} alt="Crate Guide's turntable interface." />
	</a>
	<div class="preview">
		<h2><a href="https://crate.guide">Crate Guide</a></h2>
		<div class="links">
			<a href="https://crate.guide">crate.guide</a> |
			<a href="https://github.com/ryan-voitiskis/crate-guide">GitHub</a>
		</div>
		<p>
			Crate Guide is a DJ app designed to assist in finding compatible tracks within a users vinyl
			record collection. Records can be added manually or imported from your Discogs collection.
			Audio features from your tracks can then be imported from Spotify through a mostly automated
			process.
		</p>
		<p>
			The app was built using Vue.js for the front-end and Express.js on the back-end connecting to
			a MongoDB database. Authenticated requests are made to the Discogs API using OAuth 1.0, and
			OAuth 2.0 with the Spotify API.
		</p>
	</div>
</article>

<article class="project flipped">
	<a href="https://panel-layout-generator.com" class="image-stack clean">
		<img src={panelLayoutGeneratorImage} alt="Panel layout generators main interface." />
	</a>
	<div class="preview">
		<h2><a href="https://panel-layout-generator.com">Panel layout generator</a></h2>
		<div class="links">
			<a href="https://panel-layout-generator.com">panel-layout-generator.com</a> |
			<a href="https://github.com/ryan-voitiskis/panel-layout-generator">GitHub</a>
		</div>
		<p>
			Panel layout generator is a simple layout generator for square acoustic panel installations. A
			friend of mine was installing acoustic panels using a variety of colours. Since his
			installations were constrained by specific quantities of each colour, and he did not want
			adjacent panels to be of the same colour, he had to plan the layout carefully. This app is a
			quick solution I threw together to solve his problem. Panel colours can be added with their
			quantities and the number of rows and columns adjusted. A random layout is generated upon any
			changes.
		</p>
		<p>
			The app was built using Vue.js, with the only other dependencies being <a
				href="https://pinia.vuejs.org/">Pinia</a
			>
			and <a href="https://vue-accessible-color-picker.netlify.app/">vue-accessible-color-picker</a>
		</p>
	</div>
</article>

<style lang="scss">
	.intro {
		padding: 0 10px;
		max-width: var(--page-width);
		margin: 0 auto;
	}

	.project {
		display: grid;
		grid-template-columns: 560px 1fr;
		grid-template-rows: 1fr;
		grid-gap: 60px;
		margin-bottom: 100px;
		padding: 0 10px;
		.preview {
			grid-area: 1 / 2 / 2 / 3;
			display: flex;
			flex-direction: column;
			h2 {
				font-size: 2rem;
				a {
					color: var(--heading-text);
					text-decoration: none;
				}
			}
			.links {
				margin-bottom: 10px;
				color: var(--text-soft);
				a {
					color: var(--project-link-text);
					&:hover {
						color: var(--link-hover);
					}
				}
			}
		}
		.image-stack {
			grid-area: 1 / 1 / 2 / 2;
			img {
				max-width: 100%;
				object-fit: contain;
				transition: box-shadow ease-in-out 0.2s;
			}
			&:hover img {
				box-shadow: -6px 6px 0px 0px var(--primary);
			}
		}
	}

	@media (min-width: 1061px) {
		.project.flipped {
			grid-template-columns: 1fr 560px;
			h2,
			p,
			.links {
				text-align: right;
			}
			.image-stack {
				grid-area: 1 / 2 / 2 / 3;
			}
			.preview {
				grid-area: 1 / 1 / 2 / 2;
			}
			.image-stack:hover img {
				box-shadow: 6px 6px 0px 0px var(--primary);
			}
		}
	}

	@media (max-width: 1200px) {
		.project {
			grid-template-columns: 500px 1fr;
			grid-gap: 40px;
		}
	}

	@media (max-width: 1120px) {
		.project {
			grid-template-columns: 480px 1fr;
			grid-gap: 20px;
		}
	}

	@media (max-width: 1060px) {
		.project {
			grid-template-columns: 1fr;
			grid-template-rows: auto;
			max-width: var(--page-width);
			margin: 0 auto 80px;
			.image-stack {
				grid-area: 1 / 1 / 2 / 2;
			}
			.preview {
				grid-area: 2 / 1 / 3 / 2;
			}
		}
	}

	@media (max-width: 600px) {
		.project {
			grid-template-columns: 1fr;
		}
	}
</style>
