// OLD/src/lib/components/ModalContainer.svelte
<script lang="ts">
	export let modalIsOpen: boolean = false

	export function openModal() {
		modalIsOpen = true
		document.addEventListener('keydown', (e) => {
			if (e.key === 'Escape') {
				closeModal()
			}
		})
	}

	function closeModal() {
		modalIsOpen = false
	}
</script>

<button class="clean modal-backdrop" class:open={modalIsOpen} on:click={closeModal}>
	<div class="modal">
		<slot />
	</div>
</button>

<style lang="scss">
	.modal-backdrop {
		position: fixed;
		background: var(--modal-backdrop);
		backdrop-filter: blur(10px) grayscale(0.8);
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		z-index: 99;
		display: none;
		&.open {
			display: flex;
		}
	}

	.modal {
		border-radius: 10px;
		z-index: 100;
		display: flex;
		flex-direction: column;
		max-width: v-bind(width);
		max-width: 100%;
		margin: 10px;
	}
</style>

// src/components/ModalContainer.vue
<script setup lang="ts">
import { defineModel, onBeforeUnmount, watchEffect } from 'vue'

const show = defineModel({ default: false, type: Boolean })

function escapeClose(e: KeyboardEvent) {
	if (e.key === 'Escape') show.value = false
}

function onClose() {
	if (!document) return
	document.body.style.overflow = 'visible'
	document.body.removeEventListener('keydown', escapeClose)
}

function onOpen() {
	if (!document) return
	document.body.addEventListener('keydown', escapeClose)
	document.body.style.overflow = 'hidden' // prevent scrolling of body when modal shown
}

onBeforeUnmount(() => {
	document.body.style.overflow = 'visible'
	document.body.removeEventListener('keydown', escapeClose)
})

watchEffect(() => {
	if (show.value) onOpen()
	else onClose()
})
</script>

<template>
	<div
		class="fixed left-0 top-0 z-50 flex h-full w-full items-center justify-center bg-backdrop backdrop-blur"
		:class="{ '!z-[-1]': !show }"
		@click.self="show = false"
	>
		<div class="max-h-screen" role="dialog" aria-modal="true">
			<slot />
		</div>
	</div>
</template>
