// src/routes/projects/+page.svelte
<script lang="ts">
	import type { PageData } from './$types'
	import ImageGallery from '$lib/components/ImageGallery.svelte'
	import type ImageData from '$lib/types/ImageData'

	export let data: PageData
	let crateGuideGallery: ImageGallery
	let panelLayoutGeneratorGallery: ImageGallery

	import cg1 from '$lib/images/crate-guide/1.png'
	import cg2 from '$lib/images/crate-guide/2.png'
	import cg3 from '$lib/images/crate-guide/3.png'
	import cg4 from '$lib/images/crate-guide/4.png'
	import cg5 from '$lib/images/crate-guide/5.png'
	import cg6 from '$lib/images/crate-guide/6.png'
	import cg7 from '$lib/images/crate-guide/7.png'

	import plg1 from '$lib/images/panel-layout-generator/1.png'
	import plg2 from '$lib/images/panel-layout-generator/2.png'
	import plg3 from '$lib/images/panel-layout-generator/3.png'

	const crateGuideImages: ImageData[] = [
		{ src: cg1, alt: `Crate Guide's turntable interface.` },
		{ src: cg2, alt: `Crate Guide's session interface with light theme.` },
		{ src: cg3, alt: `Crate Guide's session interface with dark theme.` },
		{ src: cg4, alt: `Crate Guide's Spotify audio features interface.` },
		{ src: cg5, alt: `Crate Guide's progress modal interface.` },
		{ src: cg6, alt: `Crate Guide's settings modal interface.` },
		{ src: cg7, alt: `Crate Guide's edit track modal interface.` }
	]

	const panelLayoutGeneratorImages: ImageData[] = [
		{ src: plg1, alt: `Panel layout generators main interface.` },
		{ src: plg2, alt: `Panel layout generators main interface with grid number.` },
		{ src: plg3, alt: `Panel layout generators add colour interface` }
	]
</script>

<div class="intro">
	<h1>Projects</h1>
	<p>
		Here's a couple of projects I've been working on recently. I would love to hear your feeback at <a
			href="mailto:ryanvoitiskis@pm.me">ryanvoitiskis@pm.me</a
		>
	</p>
	<br />
</div>

<article class="project">
	<button class="image-stack clean" on:click={() => crateGuideGallery.openInModal(0)}>
		<img src={crateGuideImages[0].src} alt={crateGuideImages[0].alt} />
	</button>
	<div class="preview">
		<h2><a href="https://crate.guide">Crate Guide</a></h2>
		<div class="links">
			<a href="https://crate.guide">crate.guide</a> |
			<a href="https://github.com/ryan-voitiskis/crate-guide">GitHub</a>
		</div>
		<p>
			Crate Guide is a DJ app designed to assist in finding compatible tracks within a users vinyl
			record collection. Records can be added manually or imported from your Discogs collection.
			Audio features from your tracks can then be imported from Spotify through a mostly automated
			process.
		</p>
		<p>
			The app was built using Vue.js for the front-end and Express.js on the back-end connecting to
			a MongoDB database. Authenticated requests are made to the Discogs API using OAuth 1.0, and
			OAuth 2.0 with the Spotify API.
		</p>
	</div>
</article>

<article class="project flipped">
	<button class="image-stack clean" on:click={() => panelLayoutGeneratorGallery.openInModal(0)}>
		<img src={panelLayoutGeneratorImages[0].src} alt={panelLayoutGeneratorImages[0].alt} />
	</button>
	<div class="preview">
		<h2><a href="https://panel-layout-generator.com">Panel layout generator</a></h2>
		<div class="links">
			<a href="https://panel-layout-generator.com">panel-layout-generator.com</a> |
			<a href="https://github.com/ryan-voitiskis/panel-layout-generator">GitHub</a>
		</div>
		<p>
			Panel layout generator is a simple layout generator for square acoustic panel installations. A
			friend of mine was installing acoustic panels using a variety of colours. Since his
			installations were constrained by specific quantities of each colour, and he did not want
			adjacent panels to be of the same colour, he had to plan the layout carefully. This app is a
			quick solution I threw together to solve his problem. Panel colours can be added with their
			quantities and the number of rows and columns adjusted. A random layout is generated upon any
			changes.
		</p>
		<p>
			The app was built using Vue.js, with the only other dependencies being <a
				href="https://pinia.vuejs.org/">Pinia</a
			>
			and <a href="https://vue-accessible-color-picker.netlify.app/">vue-accessible-color-picker</a>
		</p>
	</div>
</article>

<ImageGallery images={crateGuideImages} withPreviews={false} bind:this={crateGuideGallery} />
<ImageGallery
	images={panelLayoutGeneratorImages}
	withPreviews={false}
	bind:this={panelLayoutGeneratorGallery}
/>

<style lang="scss">
	.intro {
		padding: 0 10px;
		max-width: var(--page-width);
		margin: 0 auto;
	}

	.project {
		display: grid;
		grid-template-columns: 560px 1fr;
		grid-template-rows: 1fr;
		grid-gap: 60px;
		margin-bottom: 100px;
		padding: 0 10px;
		.preview {
			grid-area: 1 / 2 / 2 / 3;
			display: flex;
			flex-direction: column;
			h2 {
				font-size: 2rem;
				a {
					color: var(--heading-text);
					text-decoration: none;
				}
			}
			.links {
				margin-bottom: 10px;
				color: var(--text-soft);
				a {
					color: var(--text-soft);
					&:hover {
						color: var(--primary);
					}
				}
			}
		}
		.image-stack {
			grid-area: 1 / 1 / 2 / 2;
			img {
				max-width: 100%;
				object-fit: contain;
			}
			&:hover img {
				box-shadow: -6px 6px 0px 0px var(--primary);
			}
		}
	}

	@media (min-width: 1061px) {
		.project.flipped {
			grid-template-columns: 1fr 560px;
			h2,
			p,
			.links {
				text-align: right;
			}
			.image-stack {
				grid-area: 1 / 2 / 2 / 3;
				height: auto !important; /* Add this */
			}
			.preview {
				grid-area: 1 / 1 / 2 / 2;
				height: auto !important; /* Add this */
			}
			.image-stack:hover img {
				box-shadow: 6px 6px 0px 0px var(--primary);
			}
		}
	}

	@media (max-width: 1200px) {
		.project {
			grid-template-columns: 500px 1fr;
			grid-gap: 40px;
		}
	}

	@media (max-width: 1120px) {
		.project {
			grid-template-columns: 480px 1fr;
			grid-gap: 20px;
		}
	}

	@media (max-width: 1060px) {
		.project {
			grid-template-columns: 1fr;
			grid-template-rows: auto;
			max-width: var(--page-width);
			margin: 0 auto 80px;
			.image-stack {
				grid-area: 1 / 1 / 2 / 2;
				height: auto !important; /* Add this */
				img {
					height: auto !important; /* Add this */
				}
			}
			.preview {
				grid-area: 2 / 1 / 3 / 2;
				height: auto; /* Add this */
			}
		}
	}

	@media (max-width: 600px) {
		.project {
			grid-template-columns: 1fr;
		}
	}
</style>

// pages/projects.vue
<template>
	<div>
		<div class="intro">
			<h1>Projects</h1>
			<p>
				Here's a couple of projects I've been working on recently. I would love
				to hear your feeback at
				<a href="mailto:ryanvoitiskis@pm.me">ryanvoitiskis@pm.me</a>
			</p>
			<br />
		</div>

		<article class="project">
			<a href="https://crate.guide" class="image-stack clean">
				<!-- <img src="{crateGuideImage}" alt="Crate Guide's turntable interface." /> -->
			</a>
			<div class="preview">
				<h2><a href="https://crate.guide">Crate Guide</a></h2>
				<div class="links">
					<a href="https://crate.guide">crate.guide</a> |
					<a href="https://github.com/ryan-voitiskis/crate-guide">GitHub</a>
				</div>
				<p>
					Crate Guide is a DJ app designed to assist in finding compatible
					tracks within a users vinyl record collection. Records can be added
					manually or imported from your Discogs collection. Audio features from
					your tracks can then be imported from Spotify through a mostly
					automated process.
				</p>
				<p>
					The app was built using Vue.js for the front-end and Express.js on the
					back-end connecting to a MongoDB database. Authenticated requests are
					made to the Discogs API using OAuth 1.0, and OAuth 2.0 with the
					Spotify API.
				</p>
			</div>
		</article>

		<article class="project flipped">
			<a href="https://panel-layout-generator.com" class="image-stack clean">
				<!-- <img
					src="{panelLayoutGeneratorImage}"
					alt="Panel layout generators main interface."
				/> -->
			</a>
			<div class="preview">
				<h2>
					<a href="https://panel-layout-generator.com">
						Panel layout generator
					</a>
				</h2>
				<div class="links">
					<a href="https://panel-layout-generator.com">
						panel-layout-generator.com
					</a>
					|
					<a href="https://github.com/ryan-voitiskis/panel-layout-generator">
						GitHub
					</a>
				</div>
				<p>
					Panel layout generator is a simple layout generator for square
					acoustic panel installations. A friend of mine was installing acoustic
					panels using a variety of colours. Since his installations were
					constrained by specific quantities of each colour, and he did not want
					adjacent panels to be of the same colour, he had to plan the layout
					carefully. This app is a quick solution I threw together to solve his
					problem. Panel colours can be added with their quantities and the
					number of rows and columns adjusted. A random layout is generated upon
					any changes.
				</p>
				<p>
					The app was built using Vue.js, with the only other dependencies being
					<a href="https://pinia.vuejs.org/">Pinia</a> and
					<a href="https://vue-accessible-color-picker.netlify.app/">
						vue-accessible-color-picker
					</a>
				</p>
			</div>
		</article>
	</div>
</template>

<style lang="scss">
.intro {
	padding: 0 10px;
	max-width: 860px;
	margin: 0 auto;
}

.project {
	display: grid;
	grid-template-columns: 560px 1fr;
	grid-template-rows: 1fr;
	grid-gap: 60px;
	margin-bottom: 100px;
	padding: 0 10px;
	.preview {
		grid-area: 1 / 2 / 2 / 3;
		display: flex;
		flex-direction: column;
		h2 {
			font-size: 2rem;
			a {
				color: var(--heading-text);
				text-decoration: none;
			}
		}
		.links {
			margin-bottom: 10px;
			color: var(--text-soft);
			a {
				color: var(--project-link-text);
				&:hover {
					color: var(--link-hover);
				}
			}
		}
	}
	.image-stack {
		grid-area: 1 / 1 / 2 / 2;
		img {
			max-width: 100%;
			object-fit: contain;
			transition: box-shadow ease-in-out 0.2s;
		}
		&:hover img {
			box-shadow: -6px 6px 0px 0px var(--primary);
		}
	}
}

@media (min-width: 1061px) {
	.project.flipped {
		grid-template-columns: 1fr 560px;
		h2,
		p,
		.links {
			text-align: right;
		}
		.image-stack {
			grid-area: 1 / 2 / 2 / 3;
		}
		.preview {
			grid-area: 1 / 1 / 2 / 2;
		}
		.image-stack:hover img {
			box-shadow: 6px 6px 0px 0px var(--primary);
		}
	}
}

@media (max-width: 1200px) {
	.project {
		grid-template-columns: 500px 1fr;
		grid-gap: 40px;
	}
}

@media (max-width: 1120px) {
	.project {
		grid-template-columns: 480px 1fr;
		grid-gap: 20px;
	}
}

@media (max-width: 1060px) {
	.project {
		grid-template-columns: 1fr;
		grid-template-rows: auto;
		max-width: 860px;
		margin: 0 auto 80px;
		.image-stack {
			grid-area: 1 / 1 / 2 / 2;
		}
		.preview {
			grid-area: 2 / 1 / 3 / 2;
		}
	}
}

@media (max-width: 600px) {
	.project {
		grid-template-columns: 1fr;
	}
}
</style>
